### ISSUE TITLE
MCQ/GMCQ items are not selectable in Safari on iOS

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt-contrib-mcq#203]
### Subject of the issue/enhancement/features
When attempting to answer an MCQ/GMCQ component on Safari on iOS it is not possible to select an item which then prevents the question from being submitted.

### Your environment
F/W: v5.28.4
MCQ: v7.3.6
GMCQ: 7.3.6
Safari on IOS - 16.3.1
iPhone 13 Pro and iPad

### Steps to reproduce
Create a course
Add an MCQ or GMCQ
Publish course
Launch on iOS
Attempt to select an answer

### Expected behaviour
Answer should be selected and submit button becomes active

### Actual behaviour
Answer is not selected and the submit button remains disabled

**Comment by eleanor-heath** [comment]
After the release - selectable now on iOS devices for radio buttons but not checkboxes when multiple answers are selected - looking into the issue where multiple items are not able to be selected.

**Comment by oliverfoster** [comment]
Probably needs onClick as well as onChange, we've been back and forth on this for a while. Irritating. It sounds as though the tap in iOS does the focus but not the tick. Probably as the label is being tapped rather than the actual input, which ios hidden? Something along those lines?

**Comment by oliverfoster** [comment]
https://stackoverflow.com/questions/11840775/check-box-label-click-in-ipad maybe?

**Comment by eleanor-heath** [comment]
@oliverfoster I think it does get into the onFocusItem function, its just that this.model.get('_isRadio') from the code below is returning null when inside checkboxes. It seems if you revert the update that was made in here https://github.com/adaptlearning/adapt-contrib-mcq/pull/195/files both radios and checkboxes work in iOS but we possibly do not want to do that as then that would revert the fix for not being able to select a previously selected answer on question reset.

```
if (this.model.get('_isRadio')) {
      this.onItemSelect(event);
      return;
    }
    ```

**Comment by eleanor-heath** [comment]
@oliverfoster good news - I have a fix for the issue -  about to put it up for review

**Comment by oliverfoster** [comment]
Awesome, will endevaour to check it out today. Good news certainly.

**Comment by eleanor-heath** [comment]
Thanks @oliverfoster
