### ISSUE TITLE
Individual feedbacks with multiple attempts

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-mcq#94]
Is there a reason why https://github.com/adaptlearning/adapt-contrib-mcq/commit/9764c043842cb21bffc1313cdf7e984b741bb23d doesn't offer different feedbacks for multiple attempts like other feedback types?

**Comment by moloko** [comment]
To be honest, it's because we were just restoring functionality that is currently available in the master branch (of adapt_framework) but which got removed during a re-write of questionView.js

As this didn't originally have 'not final' option-specific feedback we didn't even think to put it in...

You make a good point though.

I think this should be a question for the design team as to whether this would be useful or they are happy to stick with generic 'not final' feedback.

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#852
